name: build

on:
  - pull_request
  - push

jobs:
  tests:
    name: PHP-${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.2"
          - "8.3"
        composer:
          - "dev-main"

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP.
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}

      - name: Install composer
        run: composer require --dev "composer/composer:${{ matrix.composer }}" --update-with-dependencies

      - name: Run tests with phpunit
        run: |
          vendor/bin/phpunit --verbose --colors=always
          cd tests/scripts && sh run.sh
